export const messages = {
  en: {
    message: {
      courses: "Courses",
      converter: "Converter",
      base: "Base currency",
      currConverter: "Currency Converter",
      currValutes: "Current Quotes",
      home: "Main",
      have: "I have",
      want: "I want to buy",
      eur: "EURO",
      usd: "USD",

      RUB: "Russian ruble",
      AUD: "Australian dollar",
      AZN: "Azerbaijani manat",
      GBP: "United Kingdom pound",
      AMD: "Armenian dram",
      BYN: "Belarusian ruble",
      BGN: "Bulgarian Lev",
      BRL: "Brazilian real",
      HUF: "Hungarian forint",
      HKD: "Hong Kong dollars",
      DKK: "Danish kroner",
      USD: "Danish kroner",
      EUR: "Euro",
      INR: "Indian Rupees",
      KZT: "Kazakh tenge",
      CAD: "Canadian dollar",
      KGS: "Kyrgyz som",
      CNY: "Chinese Yuan",
      MDL: "Moldavian lei",
      NOK: "Norwegian kroner",
      PLN: "Polish Zloty",
      RON: "Romanian leu",
      XDR: "SDR(Special Drawing Rights)",
      SGD: "Singapore dollar",
      TJS: "Tajik somoni",
      TRY: "Turkish lira",
      TMT: "New Turkmen manat",
      UZS: "Uzbek sums",
      UAH: "Ukrainian hryvnia",
      CZK: "CZK",
      SEK: "Swedish kroner",
      CHF: "Swiss Franc",
      ZAR: "South African rand",
      KRW: "Won the Republic of Korea",
      JPY: "Japanese yen",
    },
  },
  ru: {
    message: {
      courses: "Курсы",
      converter: "Конвертер",
      base: "Базовая валюта",
      currConverter: "Конвертер валют",
      currValutes: "Текущие котировки",
      have: "У меня есть",
      want: "Хочу приобрести",
      eur: "ЕВРО",
      usd: "ДОЛЛАР США",
      home: "Главная",

      RUB: "Российский рубль",
      AUD: "Австралийский доллар",
      AZN: "Азербайджанский манат",
      GBP: "Фунт стерлингов Соединенного королевства",
      AMD: "Армянских драмов",
      BYN: "Белорусский рубль",
      BGN: "Болгарский лев",
      BRL: "Бразильский реал",
      HUF: "Венгерских форинтов",
      HKD: "Гонконгских долларов",
      DKK: "Датских крон",
      USD: "Датских крон",
      EUR: "Евро",
      INR: "Индийских рупий",
      KZT: "Казахстанских тенге",
      CAD: "Канадский доллар",
      KGS: "Киргизских сомов",
      CNY: "Китайских юаней",
      MDL: "Молдавских леев",
      NOK: "Норвежских крон",
      PLN: "Польский злотый",
      RON: "Румынский лей",
      XDR: "СДР(специальные права заимствования)",
      SGD: "Сингапурский доллар",
      TJS: "Таджикских сомони",
      TRY: "Турецких лир",
      TMT: "Новый туркменский манат",
      UZS: "Узбекских сумов",
      UAH: "Украинских гривен",
      CZK: "Чешских крон",
      SEK: "Шведских крон",
      CHF: "Швейцарский франк",
      ZAR: "Южноафриканских рэндов",
      KRW: "Вон Республики Корея",
      JPY: "Японских йен",
    },
  },
};
